### ISSUE TITLE
Diificulty switching from 1 to 2

### ISSUE THREAD

**Issue by nekrut** [ialbert/pyblue#6]
Trying to serve an old site written for pyblue 1.2 getting this:

`WARNING	pyblue.__init__	unable to import context module: context.py`

What are the steps for switching to pyblue 2 for sites maintained with pyblue 1.2?

**Comment by ialbert** [comment]
in principle the only the tags need to be rewritten to the new format for example

from `${link "context"}  to `{% link "context" %} `

the python module loading should keep working the same way.

in practice I might have missed something, send me the zip file

**Comment by nekrut** [comment]
How do I customize with fontsawesome and other bootstrap themes?

**Comment by ialbert** [comment]
The new templates follow the django syntax for extending. I have added two examples to the distribution

This would be the extended template:

https://github.com/ialbert/pyblue/blob/master/docs/extend.html

The base template would have the new resources, css etc:

https://github.com/ialbert/pyblue/blob/master/docs/base.html

**Comment by nekrut** [comment]
thanks! I think I got it working.
